# Generated by Django 4.1 on 2022-08-22 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=50)),
                ('about_author', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('git_url', models.URLField()),
                ('insta_url', models.URLField()),
                ('full_name', models.TextField(max_length=70)),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=50)),
                ('team_position', models.CharField(max_length=50)),
                ('full_name', models.TextField(max_length=70)),
                ('date_of_birth', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('about_member', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('git_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('twiter_url', models.URLField()),
                ('github_userid', models.CharField(max_length=30)),
                ('main', models.BooleanField(default=False)),
                ('mainwork', models.CharField(blank=True, max_length=170)),
                ('mainintro', models.CharField(blank=True, max_length=570)),
                ('mainlocation', models.CharField(blank=True, max_length=570)),
                ('main_profile_picture', models.ImageField(blank=True, upload_to='')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilltopic', models.CharField(max_length=50)),
                ('skillpercentage', models.IntegerField()),
                ('member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='posts.team')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
                ('gaming', models.BooleanField()),
                ('content', tinymce.models.HTMLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
                ('categories', models.ManyToManyField(to='posts.category')),
                ('next_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='next', to='posts.post')),
                ('previous_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='previous', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=36)),
                ('position', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=50)),
                ('to_year', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience',
                                           to='posts.team')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=36)),
                ('location', models.CharField(max_length=100)),
                ('from_year', models.CharField(max_length=50)),
                ('to_year', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education',
                                           to='posts.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                           to='posts.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
