# Generated by Django 5.2.8 on 2025-11-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='team',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_member',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_userid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mainintro',
            field=models.CharField(blank=True, max_length=570, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mainlocation',
            field=models.CharField(blank=True, max_length=570, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mainwork',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
