# Generated by Django 5.2.8 on 2025-11-20 22:47

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=posts.models.avatar_path),
        ),
    ]
