# Generated by Django 5.2.8 on 2025-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_remove_experience_team_remove_skill_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_in_team',
            field=models.BooleanField(default=False),
        ),
    ]
