# Generated by Django 5.2.8 on 2025-11-17 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_rename_timestamp_post_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar',
                 models.ImageField(blank=True, default='avatars/default.png', upload_to=posts.models.avatar_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
