# Generated by Django 5.2.8 on 2025-11-17 15:07

from django.db import migrations, models

import posts.models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_profile_designation_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.avatar_path),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
