# Generated by Django 3.1.3 on 2021-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
