# Generated by Django 3.1.3 on 2021-02-10 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_team_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mainwork',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
