# Generated by Django 3.1.2 on 2020-11-03 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=50)),
                ('about_member', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('git_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('tweeter_url', models.URLField()),
                ('full_name', models.TextField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
