# Generated by Django 3.1.2 on 2020-11-04 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tweeter_url',
            new_name='twiter_url',
        ),
        migrations.AddField(
            model_name='team',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='date_of_birth',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
