# Generated by Django 3.1.3 on 2021-02-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_team_mainwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mainwork',
            field=models.CharField(max_length=170),
        ),
    ]
