# Generated by Django 3.1.3 on 2021-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210210_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mainintro',
            field=models.CharField(blank=True, max_length=570),
        ),
        migrations.AlterField(
            model_name='team',
            name='mainwork',
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
