# Generated by Django 3.1.2 on 2020-11-04 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201104_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phoneno',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
