# Generated by Django 3.1.2 on 2020-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_team_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phoneno',
            field=models.CharField(max_length=12),
        ),
    ]
