# Generated by Django 3.1.3 on 2021-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210210_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mainlocation',
            field=models.CharField(blank=True, max_length=570),
        ),
    ]
