# Generated by Django 3.1.3 on 2021-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_team_mainlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='main_profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
