# Generated by Django 3.1.2 on 2020-11-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201104_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phoneno',
            field=models.CharField(max_length=13),
        ),
    ]
