# Generated by Django 3.1.3 on 2021-02-11 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_team_main_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamposition',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
