# Generated by Django 3.1.2 on 2020-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201104_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_of_birth',
            field=models.CharField(max_length=11),
        ),
    ]
