# Generated by Django 3.1.3 on 2021-02-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_team_teamposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamposition',
            new_name='team_position',
        ),
    ]
