# Generated by Django 3.1.2 on 2020-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_education_experiences_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='institution',
            field=models.CharField(max_length=36),
        ),
    ]
