# Generated by Django 3.1.2 on 2020-11-04 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201104_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
