# Generated by Django 3.1.2 on 2020-11-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_experience_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='team',
            new_name='member',
        ),
    ]
