# Generated by Django 3.1.2 on 2020-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201105_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skilltopic',
            field=models.CharField(max_length=50),
        ),
    ]
