# Generated by Django 3.1.3 on 2020-11-23 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201105_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
